CREATE DATABASE DndWebsite;

CREATE TABLE LoginData(
    UserId INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name varchar(30) NOT NULL,
    Username varchar(60) NOT NULL,
    Pwd text NOT NULL,
);

CREATE TABLE BaseInfo (
    BaseId INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CharName varchar(30) NOT NULL,
    Class varchar(20) NOT NULL,
    Lvl INT(2) NOT NULL,
    backg varchar(30) NOT NULL,
    PlayerName varchar(30),
    Race varchar(30) NOT NULL,
    Align varchar(2) NOT NULL,
    XP INT(7) NOT NULL,
    AC INT(2) NOT NULL,
    Ini INT(2) NOT NULL,
    Sp INT(3) NOT NULL,
    MaxHP INT(4) NOT NULL,
    CurHP INT(4) NOT NULL,
    HitDice varchar(5) NOT NULL,
    PassPerc INT(2) NOT NULL,
    Weapons tinytext,
    Spells text,
    Extra text NOT NULL,
    CurGold INT(11) NOT NULL,
    UserId int,
    FOREIGN KEY(UserId) REFERENCES LoginData(UserId)
);

CREATE TABLE Stats(
    StatId INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Stre INT(2) NOT NULL,
    Dex INT(2) NOT NULL,
    Con INT(2) NOT NULL,
    Inte INT(2) NOT NULL,
    Wis INT(2) NOT NULL,
    Cha INT(2) NOT NULL,
    SvStr varchar(1),
    SvDex varchar(1),
    SvCon varchar(1),
    SvInt varchar(1),
    SvWis varchar(1),
    SvCha varchar(1),
    Acro varchar(2),
    AnHa varchar(2),
    Arc varchar(2),
    Ath varchar(2),
    Dece varchar(2),
    His varchar(2),
    Ins varchar(2),
    Intim varchar(2),
    Inv varchar(2),
    Med varchar(2),
    Nat varchar(2),
    Perc varchar(2),
    Perf varchar(2),
    Pers varchar(2),
    Rel varchar(2),
    Sli varchar(2),
    Ste varchar(2),
    Sur varchar(2),
    UserId int,
    FOREIGN KEY(UserId) REFERENCES LoginData(UserId)
);
